blank_issues_enabled: false
contact_links:
  - name: 프로젝트 문서
    url: https://github.com/ikhyeon/plan_make/blob/main/README.md
    about: 프로젝트 개요와 사용법을 확인하세요
  - name: 요구사항 문서
    url: https://github.com/ikhyeon/plan_make/blob/main/REQUIREMENTS.md
    about: 상세한 프로젝트 요구사항을 확인하세요