name: 기능 요청 (Feature Request)
description: 새로운 기능이나 개선 사항을 제안합니다
title: "[FEAT] "
labels: ["enhancement"]
assignees:
  - ikhyeon
body:
  - type: markdown
    attributes:
      value: |
        새로운 기능이나 개선 사항을 제안해주세요. 가능한 구체적으로 작성해주시면 도움이 됩니다.
  
  - type: textarea
    id: feature-description
    attributes:
      label: 기능 설명
      description: 어떤 기능을 원하시나요?
      placeholder: 예) 사용자가 강의 계획을 PDF로 내보낼 수 있는 기능
    validations:
      required: true
  
  - type: textarea
    id: motivation
    attributes:
      label: 동기 및 배경
      description: 왜 이 기능이 필요한가요?
      placeholder: 예) 오프라인에서도 학습 계획을 확인할 수 있도록 하기 위해
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 인수 조건 (Acceptance Criteria)
      description: 이 기능이 완료되었다고 판단할 수 있는 조건들
      placeholder: |
        - [ ] 사용자가 PDF 내보내기 버튼을 클릭할 수 있다
        - [ ] 생성된 PDF에 모든 학습 계획 항목이 포함된다
        - [ ] PDF 다운로드가 정상적으로 작동한다
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 이 기능의 우선순위는?
      options:
        - High (높음)
        - Medium (보통)
        - Low (낮음)
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: 추가 정보
      description: 참고 자료, 스크린샷, 관련 링크 등
      placeholder: 기타 참고할 만한 정보가 있다면 작성해주세요
    validations:
      required: false