name: 작업 (Task)
description: 개발 작업, 리팩토링, 기술 개선 등의 작업
title: "[TASK] "
labels: ["task"]
assignees:
  - ikhyeon
body:
  - type: markdown
    attributes:
      value: |
        개발 작업이나 기술적 개선 사항을 작성해주세요.
  
  - type: textarea
    id: task-description
    attributes:
      label: 작업 설명
      description: 어떤 작업을 수행하나요?
      placeholder: 예) Member 엔티티에 대한 JPA Repository 및 서비스 계층 구현
    validations:
      required: true
  
  - type: dropdown
    id: task-type
    attributes:
      label: 작업 유형
      description: 어떤 종류의 작업인가요?
      options:
        - 기능 개발 (Feature Development)
        - 리팩토링 (Refactoring)
        - 인프라 설정 (Infrastructure)
        - 테스트 작성 (Testing)
        - 문서화 (Documentation)
        - 데이터베이스 (Database)
        - 설정 (Configuration)
    validations:
      required: true
  
  - type: textarea
    id: todo-list
    attributes:
      label: 수행 내역 (Todo List)
      description: 작업을 완료하기 위한 세부 단계들
      placeholder: |
        - [ ] Member 엔티티 설계 및 구현
        - [ ] MemberRepository 인터페이스 작성
        - [ ] MemberService 계층 구현
        - [ ] 단위 테스트 작성
        - [ ] 통합 테스트 작성
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 완료 조건 (Definition of Done)
      description: 이 작업이 완료되었다고 판단할 수 있는 조건들
      placeholder: |
        - [ ] 모든 단위 테스트 통과
        - [ ] 코드 리뷰 완료
        - [ ] API 문서화 업데이트
        - [ ] DB 마이그레이션 스크립트 작성
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      description: 이 작업의 우선순위는?
      options:
        - High (높음)
        - Medium (보통)
        - Low (낮음)
    validations:
      required: true
  
  - type: input
    id: estimated-hours
    attributes:
      label: 예상 소요 시간
      description: 이 작업에 예상되는 소요 시간 (시간 단위)
      placeholder: 예) 4
    validations:
      required: false
  
  - type: textarea
    id: additional-notes
    attributes:
      label: 추가 사항
      description: 참고 자료, 관련 이슈, 기술적 고려사항 등
      placeholder: 기타 참고할 만한 정보가 있다면 작성해주세요
    validations:
      required: false